Downgrade to scalacheck 1.13.5 to avoid NoSuchMethodError
cats-laws 1.x depends on scalacheck 1.13.5, which is binary-incompatible
with the newer 1.14.0 - causing NoSuchMethodErrors in law tests for
MonadError

See https://github.com/typelevel/cats/pull/2312