Revert "CORE-1442 Scenario showing simultaneous proposes on multiple validators"
This reverts commit 7c6ce39d41af46e171a7fe1c1be80393edb0541d.

The test fails because of later changes in code:

    ImportError: cannot import name 'start_bootstrap'