Storage: Ensure consistency in storing/retrieving a AsBytesList
We were storing an AsBytesList and then trying to parse it as a BytesList.

This caused the following error

```
com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
```

This resolves https://rchain.atlassian.net/browse/RHOL-248